name: ci-cd-go-workflow

on:
  push:
    branches:
      - main

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configuração do ambiente Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.2

      - name: Execução dos testes Go
        run: go test